### ISSUE TITLE
Support for multiple joins to create multiple array fields

### ISSUE THREAD

**Issue by mradamlacey** [CompassPHS/scurrynet-riverjob#2]
Wondering if `scurrynet-riverjob` supports what I understand jdbc-river supports regarding multiple joins and creating documents with arrays.  Example:

 id | name | tags[id] | tags[name] | contributors[id] | contributor[name]
----|--------|-------------|---------------|----------------------|---------------------
 1 | Post 1 | 1 | good | 1 | Bob 
 1 | Post 1 | 2 | news | 1 | Bob 
 2 | Post 2 | 1 | good | 2 | Ted 
 2 | Post 2 | 1 | good | 3 | Mike 
2 | Post 2 | 3 | misc | 2 | Ted
2 | Post 2 | 3 | misc | 3 | Mike

Would create the following documents to index in Elasticsearch:
```json
{
    "id": 1,
    "name": "Post 1",
    "tags": [
        { "id": 1, "name": "good" },
        { "id": 2, "name": "news" }
    ],
    "contributors": [
        { "id": 1, "name": "Bob" }
    ]
}
```

```json
{
    "id": 1,
    "name": "Post 2",
    "tags": [
        { "id": 1, "name": "good" },
        { "id": 3, "name": "misc" }
    ],
    "contributors": [
        { "id": 2, "name": "Ted" },
        { "id": 3, "name": "Mike" }
    ]
}
```

Uniqueness for the document rolls up to the `id` column, but the `tags` and `contributors` fields because the columns are named with brackets also rollup into unique array entries.

Is this supported?  Seems like if you use some convention that it would be possible to implement.

**Comment by futurechan** [comment]
Yes, it does, but in order to determine uniqueness (including nested objects/arrays), you must provider an ```_id``` column.

**Comment by mradamlacey** [comment]
Great news.
